config/routes.rb
Rails.application.routes.draw do

  resources :uploads, only: [:index, :new, :create, :destroy]

  devise_for :users

  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/images' => 'users#image_index'

  root 'images#index'

  get 'token/generate'
  get 'file/download'

  get 'images' => 'images#index'
  get 'images/:id' => 'images#singleimage'
  get 'images/:id/inspect' => 'images#inspect'
  get 'images/:id/exif' => 'images#exif'
  delete 'images/:id/delete' => 'images#delete'

  iiif_for 'riiif/image', at: '/iiif'


end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    An open source project –– "fork it" on <a href="https://github.com/sgbalogh/mass-vision">GitHub</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#user-util-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "img.sgbalogh", images_path, id: "logo" %>
    </div>
    <div class="collapse navbar-collapse" id="user-util-collapse">
      <div class="navbar-right">
        <ul class="nav navbar-nav">
          <li><%= link_to 'Login', user_session_path unless user_signed_in? %></li>
          <li><%= link_to current_user.email, current_user unless !user_signed_in? %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete unless !user_signed_in? %></li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>img.sgbalogh</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<div class="container">

  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>


  <%= render 'layouts/footer' %>

</div>
<% unless uhd_cookie? %>
    <script>uhd_ify_images();</script>
    <script>send_retina_param();</script>
<% end %>

</body>
</html>